name = "offhrs"
handle = "offhrs"
client_id = "93ac1547c426534f421ce570acb3bc9d"
application_url = "https://offhrs.app/api/partners/shopify/app"
embedded = false

[access_scopes]
scopes = "read_products,read_inventory"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://offhrs.app/api/partners/shopify/callback"
]

[webhooks]
api_version = "2024-10"

[[webhooks.subscriptions]]
compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
uri = "https://offhrs.app/api/webhooks/shopify"
